from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


FIRE_CREATURES = [
    CardTemplate(
        template_id="fire_creature_aschebestie",
        name="Aschebestie",
        cost=CardCost(resources=2),
        aw=2,
        vw=1,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        must_attack_each_turn=True,
    ),
    CardTemplate(
        template_id="fire_creature_aschebrecher",
        name="Aschebrecher",
        cost=CardCost(resources=2),
        aw=1,
        vw=1,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
    CardTemplate(
        template_id="fire_creature_glutbestie",
        name="Glutbestie",
        cost=CardCost(resources=3),
        aw=3,
        vw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        must_attack_each_turn=True,
    ),
    CardTemplate(
        template_id="fire_creature_glutbrecher",
        name="Glutbrecher",
        cost=CardCost(resources=3),
        aw=3,
        vw=1,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
    CardTemplate(
        template_id="fire_creature_flammenbestie",
        name="Flammenbestie",
        cost=CardCost(resources=4),
        aw=4,
        vw=3,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        must_attack_each_turn=True,
    ),
    CardTemplate(
        template_id="fire_creature_flammenbrecher",
        name="Flammenbrecher",
        cost=CardCost(resources=4),
        aw=4,
        vw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
    CardTemplate(
        template_id="fire_creature_infernobestie",
        name="Infernobestie",
        cost=CardCost(resources=5, recycle=1),
        aw=5,
        vw=4,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        must_attack_each_turn=True,
    ),
    CardTemplate(
        template_id="fire_creature_infernobrecher",
        name="Infernobrecher",
        cost=CardCost(resources=5, recycle=1),
        aw=5,
        vw=3,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
]
