from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


FIRE_CREATURES = [
    CardTemplate(
        template_id="fire_creature_bombenwicht",
        name="Bombenwicht",
        cost=CardCost(resources=1),
        aw=1,
        vw=1,
        element=Element.FIRE,
        rules_text="Beim Ausspielen erleidest du 2 Schaden.",
        self_damage_on_play=2,
    ),
    CardTemplate(
        template_id="fire_creature_funkenwicht",
        name="Funkenwicht",
        cost=CardCost(resources=1),
        aw=1,
        vw=1,
        element=Element.FIRE,
        rules_text="Kann nicht blocken.",
        cannot_block=True,
    ),
    CardTemplate(
        template_id="fire_creature_funkenkobold",
        name="Funkenkobold",
        cost=CardCost(resources=2),
        aw=2,
        vw=1,
        element=Element.FIRE,
        rules_text="Beim Ausspielen erleiden beide Spieler 1 Schaden.",
        self_damage_on_play=1,
        opponent_damage_on_play=1,
    ),
    CardTemplate(
        template_id="fire_creature_flammenrekrut",
        name="Flammenrekrut",
        cost=CardCost(resources=3),
        aw=3,
        vw=1,
        element=Element.FIRE,
        rules_text="Beim Ausspielen erleidet der Gegner 1 Schaden.",
        opponent_damage_on_play=1,
    ),
    CardTemplate(
        template_id="fire_creature_lavakrieger",
        name="Lavakrieger",
        cost=CardCost(resources=4),
        aw=4,
        vw=1,
        element=Element.FIRE,
        rules_text="Beim Ausspielen erleiden beide Spieler 3 Schaden.",
        self_damage_on_play=3,
        opponent_damage_on_play=3,
    ),
    CardTemplate(
        template_id="fire_creature_brandstifter",
        name="Brandstifter",
        cost=CardCost(resources=2, recycle=1),
        aw=2,
        vw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.IGNITE}),
        rules_text="Entzuenden. Gewinnt diese Kreatur als Angreifer den ersten Wuerfelvergleich eines Kampfes, verursacht sie 1 zusaetzlichen Schaden.",
    ),
    CardTemplate(
        template_id="fire_creature_flammenmagier",
        name="Flammenmagier",
        cost=CardCost(resources=2, recycle=2),
        aw=3,
        vw=3,
        element=Element.FIRE,
        abilities=frozenset({Ability.IGNITE}),
        rules_text="Entzuenden. Gewinnt diese Kreatur als Angreifer den ersten Wuerfelvergleich eines Kampfes, verursacht sie 1 zusaetzlichen Schaden.",
    ),
    CardTemplate(
        template_id="fire_creature_feuerwidder",
        name="Feuerwidder",
        cost=CardCost(resources=4, recycle=1),
        aw=4,
        vw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
    CardTemplate(
        template_id="fire_creature_magmabestie",
        name="Magmabestie",
        cost=CardCost(resources=5, recycle=2),
        aw=5,
        vw=4,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
    ),
    CardTemplate(
        template_id="fire_creature_infernodrache",
        name="Infernodrache",
        cost=CardCost(resources=6, recycle=3),
        aw=6,
        vw=4,
        element=Element.FIRE,
        abilities=frozenset({Ability.IGNITE, Ability.TRAMPLE}),
        rules_text="Entzuenden. Gewinnt diese Kreatur als Angreifer den ersten Wuerfelvergleich eines Kampfes, verursacht sie 1 zusaetzlichen Schaden.",
    ),
]
