from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


ENRAGED_RULES_TEXT = "Wuetend. Wenn diese Kreatur angreift, darfst du eine gegnerische Kreatur bestimmen, die sie legal blocken kann. Diese Kreatur muss sie blocken."
TRAMPLE_RULES_TEXT = "Trampelnd. Ueberschuessiger SW-Schaden, der ueber die verbleibenden LW des Blockers hinausgeht, wird dem gegnerischen Spieler zugefuegt."
ENRAGED_TRAMPLE_RULES_TEXT = f"{ENRAGED_RULES_TEXT} {TRAMPLE_RULES_TEXT}"


FIRE_CREATURES = [
    CardTemplate(
        template_id="fire_creature_glutwesen",
        name="Glutwesen",
        cost=CardCost(resources=2),
        aw=2,
        vw=2,
        lw=2,
        sw=1,
        element=Element.FIRE,
    ),
    CardTemplate(
        template_id="fire_creature_flammenwesen",
        name="Flammenwesen",
        cost=CardCost(resources=3),
        aw=3,
        vw=3,
        lw=3,
        sw=1,
        element=Element.FIRE,
    ),
    CardTemplate(
        template_id="fire_creature_glutbrecher",
        name="Glutbrecher",
        cost=CardCost(resources=2),
        aw=2,
        vw=0,
        lw=2,
        sw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
        rules_text=TRAMPLE_RULES_TEXT,
    ),
    CardTemplate(
        template_id="fire_creature_flammenbrecher",
        name="Flammenbrecher",
        cost=CardCost(resources=4),
        aw=4,
        vw=2,
        lw=4,
        sw=2,
        element=Element.FIRE,
        abilities=frozenset({Ability.TRAMPLE}),
        rules_text=TRAMPLE_RULES_TEXT,
    ),
    CardTemplate(
        template_id="fire_creature_gluthetzer",
        name="Gluthetzer",
        cost=CardCost(resources=3),
        aw=3,
        vw=0,
        lw=3,
        sw=1,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        rules_text=ENRAGED_RULES_TEXT,
    ),
    CardTemplate(
        template_id="fire_creature_flammenhetzer",
        name="Flammenhetzer",
        cost=CardCost(resources=4),
        aw=4,
        vw=2,
        lw=4,
        sw=1,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED}),
        rules_text=ENRAGED_RULES_TEXT,
    ),
    CardTemplate(
        template_id="fire_creature_infernowesen",
        name="Infernowesen",
        cost=CardCost(resources=4, recycle=1),
        aw=4,
        vw=4,
        lw=4,
        sw=2,
        element=Element.FIRE,
    ),
    CardTemplate(
        template_id="fire_creature_infernobestie",
        name="Infernobestie",
        cost=CardCost(resources=5, recycle=1),
        aw=5,
        vw=3,
        lw=5,
        sw=3,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED, Ability.TRAMPLE}),
        rules_text=ENRAGED_TRAMPLE_RULES_TEXT,
    ),
    CardTemplate(
        template_id="fire_creature_hoellenbestie",
        name="Hoellenbestie",
        cost=CardCost(resources=5, recycle=2),
        aw=6,
        vw=3,
        lw=6,
        sw=3,
        element=Element.FIRE,
        abilities=frozenset({Ability.ENRAGED, Ability.TRAMPLE}),
        rules_text=ENRAGED_TRAMPLE_RULES_TEXT,
    ),
]
