from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


FIRE_RITUALS = [
    CardTemplate(
        template_id="fire_ritual_holzvorrat",
        name="Holzvorrat",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DECK_TO_TAPPED_RESOURCES,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Lege die oberste Karte deines Decks getappt als Ressource ins Spiel.",
    ),
    CardTemplate(
        template_id="fire_ritual_kohlevorrat",
        name="Kohlevorrat",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DECK_TO_TAPPED_RESOURCES,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Lege die obersten 2 Karten deines Decks getappt als Ressourcen ins Spiel.",
    ),
    CardTemplate(
        template_id="fire_ritual_glutvision",
        name="Glutvision",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DRAW_CARDS,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=2,
        rules_text="Ziehe 2 Karten.",
    ),
    CardTemplate(
        template_id="fire_ritual_flammenvision",
        name="Flammenvision",
        cost=CardCost(resources=4),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DRAW_CARDS,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=3,
        rules_text="Ziehe 3 Karten.",
    ),
    CardTemplate(
        template_id="fire_ritual_hitzewelle",
        name="Hitzewelle",
        cost=CardCost(resources=3),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_ALL_CREATURES_AND_PLAYERS,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Fuege allen Kreaturen und Spielern 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_ritual_feuerwelle",
        name="Feuerwelle",
        cost=CardCost(resources=5),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_ALL_CREATURES_AND_PLAYERS,
        target_mode=SpellTargetMode.NONE,
        spell_amount=4,
        rules_text="Fuege allen Kreaturen und Spielern 4 Schaden zu.",
    ),
]
