from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


FIRE_RITUALS = [
    CardTemplate(
        template_id="fire_ritual_funkenwurf",
        name="Funkenwurf",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=2,
        rules_text="Füge 1 Kreatur 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_ritual_feuerball",
        name="Feuerball",
        cost=CardCost(resources=4),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE_OR_PLAYER,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=3,
        rules_text="Füge 1 Kreatur / Spieler 3 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_ritual_flammenwelle",
        name="Flammenwelle",
        cost=CardCost(resources=4),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_ALL_ENEMY_CREATURES,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Füge allen gegnerischen Kreaturen 1 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_ritual_brandopfer",
        name="Brandopfer",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.SACRIFICE_FOR_DAMAGE,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        sacrifice_own_creature_on_cast=True,
        rules_text="Opfere 1 eigene Kreatur. Füge 1 Kreatur / Spieler Schaden in Höhe ihres AW zu.",
    ),
    CardTemplate(
        template_id="fire_ritual_verbotene_glut",
        name="Verbotene Glut",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DRAW_AND_SELF_DAMAGE,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        spell_draw_count=2,
        rules_text="Ziehe 2 Karten und erleide 2 Schaden.",
    ),
]
