from __future__ import annotations

from core.models import (
    CardCost,
    CardTemplate,
    CardType,
    Element,
    ReactionTrigger,
    SpellEffect,
    SpellTargetMode,
)


FIRE_SPELLS = [
    CardTemplate(
        template_id="fire_spell_hitzeschub",
        name="Hitzeschub",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.MODIFY_DIE_RESULT,
        reaction_trigger=ReactionTrigger.AFTER_DICE_REVEALED,
        target_mode=SpellTargetMode.NONE,
        spell_amount=3,
        rules_text="Erhöhe das Ergebnis deines Würfels in diesem Vergleich um 3.",
    ),
    CardTemplate(
        template_id="fire_spell_letzter_funke",
        name="Letzter Funke",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DAMAGE_AFTER_OWN_CREATURE_DESTROYED,
        reaction_trigger=ReactionTrigger.OWN_CREATURE_DESTROYED,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=2,
        rules_text="Füge einer Kreatur oder einem Spieler 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_brandzeichen",
        name="Brandzeichen",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DAMAGE_DECLARED_BLOCKER,
        reaction_trigger=ReactionTrigger.BLOCKER_DECLARED,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Füge dem deklarierten Blocker 1 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_gegenfeuer",
        name="Gegenfeuer",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DAMAGE_OPPONENT_WHEN_TARGETED,
        reaction_trigger=ReactionTrigger.OWN_CREATURE_TARGETED,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Füge dem gegnerischen Spieler 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_flammenzorn",
        name="Flammenzorn",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.RETALIATE_DICE_DAMAGE,
        reaction_trigger=ReactionTrigger.OWN_CREATURE_DAMAGED_IN_DICE_COMPARISON,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Die gegnerische Kreatur in diesem Würfelvergleich erleidet 1 Schaden.",
    ),
]
