from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


FIRE_SPELLS = [
    CardTemplate(
        template_id="fire_spell_wutanfall",
        name="Wutanfall",
        cost=CardCost(resources=0, recycle=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=3,
        rules_text="Ein Angreifer erhaelt +3 AW fuer diesen Zug.",
    ),
    CardTemplate(
        template_id="fire_spell_raserei",
        name="Raserei",
        cost=CardCost(resources=0, recycle=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=6,
        rules_text="Ein Angreifer erhaelt +6 AW fuer diesen Zug.",
    ),
    CardTemplate(
        template_id="fire_spell_versengen",
        name="Versengen",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE_OR_PLAYER,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=1,
        rules_text="Fuege einer Kreatur oder einem Spieler 1 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_verbrennen",
        name="Verbrennen",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE_OR_PLAYER,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=2,
        rules_text="Fuege einer Kreatur oder einem Spieler 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_verkohlen",
        name="Verkohlen",
        cost=CardCost(resources=3),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE_OR_PLAYER,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=3,
        rules_text="Fuege einer Kreatur oder einem Spieler 3 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_verzehren",
        name="Verzehren",
        cost=CardCost(resources=4),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE_OR_PLAYER,
        target_mode=SpellTargetMode.CREATURE_OR_PLAYER,
        spell_amount=4,
        rules_text="Fuege einer Kreatur oder einem Spieler 4 Schaden zu.",
    ),
]
