from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, ReactionTrigger, SpellEffect, SpellTargetMode, SpellTiming


FIRE_SPELLS = [
    CardTemplate(
        template_id="fire_spell_wutanfall",
        name="Wutanfall",
        cost=CardCost(resources=0, recycle=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START,),
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=1,
        combat_aw_bonus=2,
        combat_sw_bonus=2,
        rules_text="Eine Kreatur erhaelt +2A und +2S fuer diesen Kampf.",
    ),
    CardTemplate(
        template_id="fire_spell_raserei",
        name="Raserei",
        cost=CardCost(resources=0, recycle=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START,),
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=1,
        combat_aw_bonus=4,
        combat_sw_bonus=4,
        rules_text="Eine Kreatur erhaelt +4A und +4S fuer diesen Kampf.",
    ),
    CardTemplate(
        template_id="fire_spell_versengen",
        name="Versengen",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START, ReactionTrigger.COMBAT_END),
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=1,
        rules_text="Fuege einer Kreatur 1 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_verbrennen",
        name="Verbrennen",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START, ReactionTrigger.COMBAT_END),
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=2,
        rules_text="Fuege einer Kreatur 2 Schaden zu.",
    ),
    CardTemplate(
        template_id="fire_spell_verkohlen",
        name="Verkohlen",
        cost=CardCost(resources=3),
        aw=0,
        vw=0,
        element=Element.FIRE,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START, ReactionTrigger.COMBAT_END),
        spell_effect=SpellEffect.DEAL_DAMAGE_TO_CREATURE,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=3,
        rules_text="Fuege einer Kreatur 3 Schaden zu.",
    ),
]
