STARTING_LIFE = 10

BUILDER_AI_DEBUG = 1
BUILDER_AI_DEBUG_TOP_N = 5
BUILDER_AI_DEBUG_BUILD_TOP_N = 5
BUILDER_AI_DEBUG_FLOAT_PRECISION = 2
BUILDER_AI_DEBUG_INCLUDE_WEIGHTS = 1
BUILDER_AI_DEBUG_INCLUDE_FINGERPRINTS = 1
