PHASE_MAIN_1 = "Erste Hauptphase"
PHASE_BUILDER_CREATURE = "Builder Kreatur"
PHASE_BUILDER_ABILITY = "Builder Ability"
PHASE_DECLARE_ATTACKERS = "Angreifer waehlen"
PHASE_DECLARE_BLOCKERS = "Blocker waehlen"
PHASE_DICE_BATTLE = "Wuerfelkampf"
PHASE_GAME_OVER = "Spielende"
