from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


EARTH_CREATURES = [
    CardTemplate(
        template_id="earth_creature_steinwesen",
        name="Steinwesen",
        cost=CardCost(resources=2),
        aw=2,
        vw=2,
        lw=2,
        sw=1,
        element=Element.EARTH,
    ),
    CardTemplate(
        template_id="earth_creature_felswesen",
        name="Felswesen",
        cost=CardCost(resources=3),
        aw=3,
        vw=3,
        lw=3,
        sw=1,
        element=Element.EARTH,
    ),
    CardTemplate(
        template_id="earth_creature_steinwaechter",
        name="Steinwaechter",
        cost=CardCost(resources=2),
        aw=1,
        vw=3,
        lw=2,
        sw=1,
        element=Element.EARTH,
        abilities=frozenset({Ability.VIGILANT}),
    ),
    CardTemplate(
        template_id="earth_creature_granitwaechter",
        name="Granitwaechter",
        cost=CardCost(resources=4),
        aw=2,
        vw=4,
        lw=3,
        sw=1,
        element=Element.EARTH,
        abilities=frozenset({Ability.VIGILANT}),
    ),
    CardTemplate(
        template_id="earth_creature_felsgolem",
        name="Felsgolem",
        cost=CardCost(resources=3, recycle=1),
        aw=3,
        vw=3,
        lw=3,
        sw=1,
        element=Element.EARTH,
        abilities=frozenset({Ability.MAGIC_RESISTANT}),
    ),
    CardTemplate(
        template_id="earth_creature_granitgolem",
        name="Granitgolem",
        cost=CardCost(resources=4),
        aw=2,
        vw=4,
        lw=4,
        sw=1,
        element=Element.EARTH,
        abilities=frozenset({Ability.MAGIC_RESISTANT}),
    ),
    CardTemplate(
        template_id="earth_creature_gebirgstitan",
        name="Gebirgstitan",
        cost=CardCost(resources=5),
        aw=3,
        vw=4,
        lw=4,
        sw=2,
        element=Element.EARTH,
        abilities=frozenset({Ability.VIGILANT, Ability.MAGIC_RESISTANT}),
    ),
    CardTemplate(
        template_id="earth_creature_gebirgskoloss",
        name="Gebirgskoloss",
        cost=CardCost(resources=5, recycle=1),
        aw=3,
        vw=6,
        lw=5,
        sw=2,
        element=Element.EARTH,
        abilities=frozenset({Ability.VIGILANT, Ability.MAGIC_RESISTANT}),
    ),
]
