from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


AIR_CREATURES = [
    CardTemplate(
        template_id="air_creature_windschwinge",
        name="Windschwinge",
        cost=CardCost(resources=0, recycle=1),
        aw=1,
        vw=1,
        lw=1,
        sw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
    ),
    CardTemplate(
        template_id="air_creature_sturmschwinge",
        name="Sturmschwinge",
        cost=CardCost(resources=0, recycle=2),
        aw=2,
        vw=1,
        lw=2,
        sw=2,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
    ),
    CardTemplate(
        template_id="air_creature_orkanschwinge",
        name="Orkanschwinge",
        cost=CardCost(resources=0, recycle=3),
        aw=3,
        vw=1,
        lw=3,
        sw=3,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
    ),
    CardTemplate(
        template_id="air_creature_windgeist",
        name="Windgeist",
        cost=CardCost(resources=1),
        aw=2,
        vw=0,
        lw=1,
        sw=1,
        element=Element.AIR,
    ),
    CardTemplate(
        template_id="air_creature_sturmgeist",
        name="Sturmgeist",
        cost=CardCost(resources=2),
        aw=3,
        vw=0,
        lw=1,
        sw=1,
        element=Element.AIR,
    ),
    CardTemplate(
        template_id="air_creature_orkangeist",
        name="Orkangeist",
        cost=CardCost(resources=3),
        aw=4,
        vw=0,
        lw=1,
        sw=1,
        element=Element.AIR,
    ),
    CardTemplate(
        template_id="air_creature_windwesen",
        name="Windwesen",
        cost=CardCost(resources=1),
        aw=1,
        vw=1,
        lw=1,
        sw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_sturmwesen",
        name="Sturmwesen",
        cost=CardCost(resources=2),
        aw=2,
        vw=2,
        lw=1,
        sw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_orkanwesen",
        name="Orkanwesen",
        cost=CardCost(resources=3),
        aw=3,
        vw=3,
        lw=1,
        sw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_luftelementar",
        name="Luftelementar",
        cost=CardCost(resources=3, recycle=3),
        aw=3,
        vw=3,
        lw=3,
        sw=3,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING, Ability.HASTE}),
    ),
]
