from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, Element


AIR_CREATURES = [
    CardTemplate(
        template_id="air_creature_boeengeist",
        name="Sturmkrieger",
        cost=CardCost(resources=0, recycle=1),
        aw=1,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_boeenreiter",
        name="Sturmfalke",
        cost=CardCost(resources=0, recycle=2),
        aw=1,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
        rules_text="Wenn diese Kreatur stirbt, ziehe 1 Karte.",
        draw_on_death=1,
    ),
    CardTemplate(
        template_id="air_creature_sturmfuerst",
        name="Sturmfuerst",
        cost=CardCost(resources=0, recycle=3),
        aw=1,
        vw=1,
        element=Element.AIR,
        rules_text="Schnelle Kreaturen erhalten +1 AW. Fliegende Kreaturen erhalten +1 VW.",
    ),
    CardTemplate(
        template_id="air_creature_windhuscher",
        name="Wolkenkrieger",
        cost=CardCost(resources=1),
        aw=1,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
        rules_text="Diese Kreatur muss in jedem eigenen Zug angreifen, falls sie dazu in der Lage ist.",
        must_attack_each_turn=True,
    ),
    CardTemplate(
        template_id="air_creature_windgeist",
        name="Wolkenfalke",
        cost=CardCost(resources=1),
        aw=1,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
        rules_text="Diese Kreatur kann nicht blocken.",
        cannot_block=True,
    ),
    CardTemplate(
        template_id="air_creature_himmelsspaeher",
        name="Windkrieger",
        cost=CardCost(resources=2),
        aw=2,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_sturmfalke",
        name="Windfalke",
        cost=CardCost(resources=2),
        aw=1,
        vw=2,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
    ),
    CardTemplate(
        template_id="air_creature_windklinge",
        name="Himmelskrieger",
        cost=CardCost(resources=3),
        aw=3,
        vw=1,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE}),
    ),
    CardTemplate(
        template_id="air_creature_himmelsgreif",
        name="Himmelsfalke",
        cost=CardCost(resources=3),
        aw=1,
        vw=3,
        element=Element.AIR,
        abilities=frozenset({Ability.FLYING}),
        rules_text="Wenn diese Kreatur ins Spiel kommt, ziehe 1 Karte.",
        draw_on_play=1,
    ),
    CardTemplate(
        template_id="air_creature_wolkenwaechter",
        name="Orkanreiter",
        cost=CardCost(resources=4, recycle=1),
        aw=2,
        vw=2,
        element=Element.AIR,
        abilities=frozenset({Ability.HASTE, Ability.FLYING}),
        rules_text="Wenn diese Kreatur angreift, ziehe 1 Karte.",
        draw_on_attack=1,
    ),
]
