from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


AIR_RITUALS = [
    CardTemplate(
        template_id="air_ritual_aufwind",
        name="Aufwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.REDUCE_CREATURE_COST_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Kreaturen, die du in diesem Zug ausspielst, kosten 1 Ressource weniger.",
    ),
    CardTemplate(
        template_id="air_ritual_rueckenwind",
        name="Rueckenwind",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.REDUCE_CREATURE_COST_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Kreaturen, die du in diesem Zug ausspielst, kosten 2 Ressourcen weniger.",
    ),
    CardTemplate(
        template_id="air_ritual_windwechsel",
        name="Windwechsel",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.RETURN_CREATURES_FROM_OWN_DISCARD_TO_HAND,
        target_mode=SpellTargetMode.DISCARD_CREATURE_CARD,
        spell_amount=1,
        rules_text="Nimm 1 Kreaturenkarte aus deinem Ablagestapel auf deine Hand.",
    ),
    CardTemplate(
        template_id="air_ritual_sturmformation",
        name="Sturmformation",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.RETURN_CREATURES_FROM_OWN_DISCARD_TO_HAND,
        target_mode=SpellTargetMode.DISCARD_CREATURE_CARD,
        spell_amount=2,
        rules_text="Nimm 2 Kreaturenkarten aus deinem Ablagestapel auf deine Hand.",
    ),
    CardTemplate(
        template_id="air_ritual_turbulenz",
        name="Turbulenz",
        cost=CardCost(recycle=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DISCARD_HAND_AND_DRAW,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=3,
        rules_text="Lege deine Hand auf den Ablagestapel. Ziehe 3 Karten.",
    ),
    CardTemplate(
        template_id="air_ritual_nachwehen",
        name="Nachwehen",
        cost=CardCost(recycle=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DISCARD_HAND_AND_DRAW,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=5,
        rules_text="Lege deine Hand auf den Ablagestapel. Ziehe 5 Karten.",
    ),
]
