from __future__ import annotations

from core.models import Ability, CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


AIR_RITUALS = [
    CardTemplate(
        template_id="air_ritual_aufwind",
        name="Aufwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.REDUCE_CREATURE_COST_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Kreaturen, die du in diesem Zug ausspielst, kosten 1 Ressource weniger.",
    ),
    CardTemplate(
        template_id="air_ritual_rueckenwind",
        name="Rückenwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.GRANT_HASTE_OR_FLYING_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        rules_text="Eine Kreatur erhält bis zum Ende des Zuges Schnell oder Fliegend.",
    ),
    CardTemplate(
        template_id="air_ritual_windwechsel",
        name="Windwechsel",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DRAW_TWO_THEN_DISCARD_ONE,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=2,
        rules_text="Ziehe 2 Karten. Wirf eine Karte ab.",
    ),
    CardTemplate(
        template_id="air_ritual_sturmformation",
        name="Sturmformation",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.BUFF_ATTACKERS_DICE_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Angreifende Kreaturen erhalten in diesem Zug +2 auf ihre Würfelergebnisse.",
    ),
    CardTemplate(
        template_id="air_ritual_turbulenz",
        name="Turbulenz",
        cost=CardCost(resources=3),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.RETURN_OWN_AND_ENEMY_CREATURE_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        rules_text="Nimm eine eigene und eine gegnerische Kreatur auf die Hand ihrer Besitzer zurück.",
    ),
]
