from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


AIR_RITUALS = [
    CardTemplate(
        template_id="air_ritual_aufwind",
        name="Aufwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.REDUCE_CREATURE_COST_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Kreaturen, die du in diesem Zug ausspielst, kosten 1 Ressource weniger.",
    ),
    CardTemplate(
        template_id="air_ritual_rueckenwind",
        name="Rueckenwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_UNTIL_END_OF_TURN,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=5,
        rules_text="Eine Kreatur erhaelt bis zum Ende des Zuges +5 AW.",
    ),
    CardTemplate(
        template_id="air_ritual_windwechsel",
        name="Windwechsel",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DRAW_TWO_THEN_DISCARD_ONE,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=3,
        rules_text="Ziehe 3 Karten. Wirf eine Karte ab.",
    ),
    CardTemplate(
        template_id="air_ritual_sturmformation",
        name="Sturmformation",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.DISCARD_HAND_AND_DRAW_THREE,
        target_mode=SpellTargetMode.NONE,
        spell_draw_count=3,
        rules_text="Lege deine Hand auf den Ablagestapel. Ziehe 3 Karten.",
    ),
    CardTemplate(
        template_id="air_ritual_turbulenz",
        name="Turbulenz",
        cost=CardCost(recycle=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.RITUAL,
        spell_effect=SpellEffect.RETURN_TWO_CREATURES_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        rules_text="Nimm zwei Kreaturen auf die Haende ihrer Besitzer zurueck.",
    ),
]
