from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


AIR_SPELLS = [
    CardTemplate(
        template_id="air_spell_ausweichen",
        name="Ausweichen",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.RETURN_OWN_FIGHTING_CREATURE_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        rules_text="Nimm eine eigene kämpfende Kreatur auf die Hand zurück.",
    ),
    CardTemplate(
        template_id="air_spell_windstoss",
        name="Windstoß",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.REROLL_OWN_UNUSED_COMBAT_DIE,
        target_mode=SpellTargetMode.NONE,
        rules_text="Wirf einen unbenutzten Würfel einer eigenen kämpfenden Kreatur neu.",
    ),
    CardTemplate(
        template_id="air_spell_boeenschub",
        name="Böenschub",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.ADD_TWENTY_TO_OWN_UNUSED_COMBAT_DIE,
        target_mode=SpellTargetMode.NONE,
        spell_amount=20,
        rules_text="Erhöhe das Ergebnis eines unbenutzten Würfels einer eigenen kämpfenden Kreatur um 20.",
    ),
    CardTemplate(
        template_id="air_spell_windrausch",
        name="Windrausch",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DOUBLE_UNBLOCKED_ATTACK_DAMAGE,
        target_mode=SpellTargetMode.NONE,
        rules_text="Eine ungeblockte angreifende Kreatur verursacht doppelt so viel Schaden.",
    ),
    CardTemplate(
        template_id="air_spell_nachwehen",
        name="Nachwehen",
        cost=CardCost(recycle=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DRAW_PER_DEATH_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Ziehe für jede Kreatur, die in diesem Zug gestorben ist, 2 Karten.",
    ),
]
