from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, SpellEffect, SpellTargetMode


AIR_SPELLS = [
    CardTemplate(
        template_id="air_spell_ausweichen",
        name="Ausweichen",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.RETURN_OWN_FIGHTING_CREATURE_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        rules_text="Nimm eine eigene Kreatur auf die Hand zurück.",
    ),
    CardTemplate(
        template_id="air_spell_windstoss",
        name="Windstoß",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.REROLL_OPEN_DIE,
        target_mode=SpellTargetMode.NONE,
        rules_text="Wirf einen Würfel erneut.",
    ),
    CardTemplate(
        template_id="air_spell_boeenschub",
        name="Böenschub",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_TO_ATTACKER_THIS_COMBAT,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=2,
        rules_text="Eine angreifende Kreatur erhält für diesen Kampf +2 AW.",
    ),
    CardTemplate(
        template_id="air_spell_windrausch",
        name="Windrausch",
        cost=CardCost(resources=2, recycle=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DOUBLE_UNBLOCKED_ATTACK_DAMAGE,
        target_mode=SpellTargetMode.NONE,
        rules_text="Deine ungeblockten angreifenden Kreaturen verursachen in diesem Kampf doppelten Spielerschaden.",
    ),
    CardTemplate(
        template_id="air_spell_nachwehen",
        name="Nachwehen",
        cost=CardCost(recycle=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_effect=SpellEffect.DRAW_PER_DEATH_THIS_TURN,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Ziehe für jede Kreatur, die in diesem Zug gestorben ist, 2 Karten.",
    ),
]
