from __future__ import annotations

from core.models import CardCost, CardTemplate, CardType, Element, ReactionTrigger, SpellEffect, SpellTargetMode, SpellTiming


AIR_SPELLS = [
    CardTemplate(
        template_id="air_spell_verwehung",
        name="Verwehung",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.INSTANT,
        spell_effect=SpellEffect.RETURN_CREATURES_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=1,
        rules_text="Nimm 1 Kreatur auf die Hand ihres Besitzers zurueck.",
    ),
    CardTemplate(
        template_id="air_spell_verwirbelung",
        name="Verwirbelung",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.INSTANT,
        spell_effect=SpellEffect.RETURN_CREATURES_TO_HAND,
        target_mode=SpellTargetMode.CREATURE,
        spell_amount=2,
        rules_text="Nimm 2 Kreaturen auf die Haende ihrer Besitzer zurueck.",
    ),
    CardTemplate(
        template_id="air_spell_jagdwind",
        name="Jagdwind",
        cost=CardCost(resources=1),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START,),
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_TO_OWN_ATTACKERS_THIS_COMBAT,
        target_mode=SpellTargetMode.NONE,
        spell_amount=1,
        rules_text="Angreifende Kreaturen erhalten fuer diesen Kampf +1 AW.",
    ),
    CardTemplate(
        template_id="air_spell_sturmjagd",
        name="Sturmjagd",
        cost=CardCost(resources=2),
        aw=0,
        vw=0,
        element=Element.AIR,
        card_type=CardType.SPELL,
        spell_timing=SpellTiming.COMBAT,
        legal_reaction_windows=(ReactionTrigger.COMBAT_START,),
        spell_effect=SpellEffect.GRANT_ATTACK_BONUS_TO_OWN_ATTACKERS_THIS_COMBAT,
        target_mode=SpellTargetMode.NONE,
        spell_amount=2,
        rules_text="Angreifende Kreaturen erhalten fuer diesen Kampf +2 AW.",
    ),
]
